# name: Trivy Vulnerability Scanner

# on:
#   push:
#     paths:
#       - '**/package*.json'
#       - '**/.github/workflows/**'

# jobs:
#   scan:
#     name: Scan for Vulnerabilities
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4
#       - name: Run Trivy vulnerability scanner (filesystem scan)
#         uses: aquasecurity/trivy-action@0.30.0
#         with:
#           scan-type: 'fs'
#           scan-ref: '.'
#           format: 'table'
#           ignore-unfixed: true
#           severity: 'CRITICAL'
#           vuln-type: 'os,library'
#           # trivyignores: .trivyignore
#       - name: Run Trivy vulnerability scanner in repo mode
#         uses: aquasecurity/trivy-action@0.28.0
#         with:
#           scan-type: 'fs'
#           format: 'sarif'
#           output: 'trivy-results.sarif'
#           severity: 'CRITICAL'

name: Trivy Vulnerability Scanner

on:
  push:
    branches:
      - main
    paths:
      - '**/package*.json'
      - '**/go.mod'
      - '**/go.sum'
      - '**/Dockerfile'
      - '.github/workflows/**'
  pull_request:
    paths:
      - '**/package*.json'
      - '**/go.mod'
      - '**/go.sum'
      - '**/Dockerfile'
      - '.github/workflows/**'


jobs:
  scan:
    name: Scan for Vulnerabilities
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 1: Run Trivy with table format to fail the build and provide clear log output.
      - name: Run Trivy vulnerability scanner (log output)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'table'
          severity: 'CRITICAL'
          ignore-unfixed: true
          # This exit-code will fail the build if CRITICAL vulnerabilities are found.
          exit-code: '1'

      # Step 2: Run Trivy again to generate a SARIF report for the GitHub Security tab.
      # This step will not fail the build.
      - name: Run Trivy vulnerability scanner (SARIF report)
        # Use 'if: always()' to ensure this step runs even if the previous one fails.
        if: always()
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          # Use exit-code '0' so this step doesn't fail the build.
          # Its only purpose is to generate the report.
          exit-code: '0'
