# name: Trivy Vulnerability Scanner

# on:
#   push:
#     paths:
#       - '**/package*.json'
#       - '**/.github/workflows/**'

# jobs:
#   scan:
#     name: Scan for Vulnerabilities
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4
#       - name: Run Trivy vulnerability scanner (filesystem scan)
#         uses: aquasecurity/trivy-action@0.30.0
#         with:
#           scan-type: 'fs'
#           scan-ref: '.'
#           format: 'table'
#           ignore-unfixed: true
#           severity: 'CRITICAL'
#           vuln-type: 'os,library'
#           # trivyignores: .trivyignore
#       - name: Run Trivy vulnerability scanner in repo mode
#         uses: aquasecurity/trivy-action@0.28.0
#         with:
#           scan-type: 'fs'
#           format: 'sarif'
#           output: 'trivy-results.sarif'
#           severity: 'CRITICAL'

name: Trivy Vulnerability Scanner

on:
  push:
    branches:
      - main
    paths:
      - '**/package*.json'
      - '**/go.mod'
      - '**/go.sum'
      - '**/Dockerfile'
      - '.github/workflows/**'
  pull_request:
    paths:
      - '**/package*.json'
      - '**/go.mod'
      - '**/go.sum'
      - '**/Dockerfile'
      - '.github/workflows/**'


jobs:
  scan:
    name: Scan for Vulnerabilities
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # This step will fail the build and print a table in the logs
      # if CRITICAL vulnerabilities are found.
      - name: Run Trivy vulnerability scanner (log output)
        uses: aquasecurity/trivy-action@0.30.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          ignore-unfixed: true
          severity: 'CRITICAL'
          vuln-type: 'os,library'
          exit-code: '1' # Important: fails the build on detection

      # This step runs ONLY IF the first one passes. For a more robust
      # report, you might want this to run always. See note below.
      - name: Run Trivy vulnerability scanner (SARIF report)
        # We add if: always() so this report is generated even if the
        # previous step fails. This ensures the security tab is always updated.
        if: always()
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH' # You might want to report HIGH severity as well
