name: Test PR #1038 on Push to Main

on:
  push:
    branches:
      - main

jobs:
  test-hardcoded-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Clone kubestellar/ui repo
        run: |
          git clone https://github.com/kubestellar/ui.git
          cd ui
          git remote add pranjal https://github.com/Pranjal6955/ui.git
          git fetch pranjal Metric
          git checkout -b testpr-985 pranjal/Metric

      - name: Run create-kubestellar-demo-env.sh
        run: |
          cd ui
          bash <(curl -s https://raw.githubusercontent.com/kubestellar/kubeflex/main/scripts/install-kubeflex.sh) --ensure-folder /usr/local/bin --strip-bin
          bash <(curl -L https://raw.githubusercontent.com/open-cluster-management-io/clusteradm/main/install.sh)
          bash <(clusteradm init)
          bash <(curl -s https://raw.githubusercontent.com/kubestellar/kubestellar/refs/tags/v0.25.1/scripts/create-kubestellar-demo-env.sh)

      - name: Install Docker and Docker Compose
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose plugin
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose-plugin

      - name: Build and run Docker Compose
        run: |
          cd ui
          docker compose up --build -d

      - name: Install Netlify CLI
        run: npm install -g netlify-cli
